services:
  postgres:
    image: postgres:16
    container_name: cyping-postgres
    environment:
      POSTGRES_USER: cyping
      POSTGRES_PASSWORD: cyping
      POSTGRES_DB: cyping
    ports:
      - "5432:5432"
    volumes:
      - cyping_pgdata:/var/lib/postgresql/data
volumes:
  cyping_pgdata: