server:
  addr: ":8080"
monitoring:
  workers: 8
  jobs_buffer: 200
  results_buffer: 200
  user_agent: "CyprusStatusMonitor/0.1 (+contact: you@example.com)"

targets:
  - name: "gov.cy"
    url: "https://cge.cyprus.gov.cy/cylogin/core/login?"
    method: "GET"
    interval: "30s"
    timeout: "5s"
    expected_status: 200

  - name: "cyprus-post"
    url: "https://www.cypruspost.post/el/login"
    method: "GET"
    interval: "60s"
    timeout: "5s"

  - name : "GESY Beneficiaries Portal"
    url : "https://portal.gesy.org.cy/"
    method: "GET"
    interval: "60s"
    timeout: "5s"
  - name : "GESY Providers Portal"
    url : "https://providers.gesy.org.cy/"
    method: "GET"
    interval: "60s"
    timeout: "5s"