server:
  addr: ":8080"
monitoring:
  workers: 8
  jobs_buffer: 200
  results_buffer: 200
  user_agent: "CyprusStatusMonitor/0.1"

targets:
  - name: "gov.cy"
    url: "https://cge.cyprus.gov.cy"
    method: "GET"
    interval: "30s"
    timeout: "10s"
    expected_status: 200
  - name : "SigmaLive"
    url : "https://www.sigmalive.com/"
    method: "GET"
    interval: "60s"
    timeout: "10s"
    expected_status: 200
  - name : "Philenews"
    url : "https://in-cyprus.philenews.com/"
    method: "GET"
    interval: "60s"
    timeout: "10s"
    expected_status: 200
  - name : "Cyprus Ministry of Education , Sport & Youth"
    url : "https://www.moec.gov.cy/en/"
    method: "GET"
    interval: "60s"
    timeout: "10s"
    expected_status: 200
  - name : "Department of Lands and Surveys"
    url : "https://portal.dls.moi.gov.cy/en/"
    method: "GET"
    interval: "60s"
    timeout: "10s"
    expected_status: 200
  - name : "Cyprus Public transportation"
    url : "https://www.publictransport.com.cy/"
    method: "GET"
    interval: "60s"
    timeout: "10s"
    expected_status: 200
  
  


